# Generated by Django 5.2.1 on 2025-05-15 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='market',
        ),
        migrations.AddField(
            model_name='product',
            name='markets',
            field=models.ManyToManyField(related_name='products', to='market_app.market'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='seller',
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ManyToManyField(related_name='products', to='market_app.seller'),
        ),
    ]
